### PR TITLE
Add a traits system

### PR DESCRIPTION
**Pull request by timholy**
OK, here's my proposal for a new `ColorTypes`. Probably the easiest way to get started is to look at the README, which you can see [here](https://github.com/timholy/ColorTypes.jl/tree/teh/traits).

To your original, the main feature is a robust "traits" system that makes it much easier to write generic code without using `@eval` everywhere. I can post the upcoming (and working!) `ColorVectorSpace` package if you want to see what I mean. You have to be running a recent julia for the tests to pass (you need https://github.com/JuliaLang/julia/pull/12645).

I've also created a `Colors` package and a branch of `Images` that both work with this. So I'm reasonably confident this works pretty well.

One question I have is, which packages do you want to "host", and which should be put elsewhere? (JuliaLang?)

### CODE REVIEW

**Comment by timholy** [comment]
The change to Images is https://github.com/timholy/Images.jl/pull/340

**Comment by SimonDanisch** [comment]
This looks really great!
I see if I can integrate it before I go to bed!
First thing I did is to also export `TransparentGray`, which you define as
a new typealias in Images.jl. Why not just export it from ColorTypes?!

2015-08-17 23:05 GMT+02:00 Tim Holy <notifications@github.com>:

**Comment by SimonDanisch** [comment]
Okay I think I have mostly integrated it.
What are your plans with `ImageMagick`!? Should I clean it up and then submit a pull request to `Images`?

**Comment by timholy** [comment]
Yeah, having the standalone ImageMagick package is a big part of the goal here. I almost finished that before I realize the "Color/ColorType" split, so I may be able to submit that momentarily. Rebasing Images on that is not something I've started, so if you'd like to take a crack at it, that would be awesome!

**Comment by timholy** [comment]
OK, here's ColorVectorSpace: https://github.com/timholy/ColorVectorSpace.jl (again, if you prefer I'm happy to host on JuliaLang or turn it over to you).

**Comment by timholy** [comment]
OK, see https://github.com/JuliaIO/ImageMagick.jl/pull/3

**Comment by timholy** [comment]
I'm going to be working on tests for the new Colors package, so I won't be touching Images for quite a few hours.

**Comment by SimonDanisch** [comment]
Great!
I'm happy to put it all under JuliaGraphics/JuliaLang/JuliaImages ;)
JuliacGraphics is a little deserted, so I'm not sure which one would be the
best.

2015-08-18 0:32 GMT+02:00 Tim Holy <notifications@github.com>:

**Comment by timholy** [comment]
Actually, I like the idea of hosting anything color-related on JuliaGraphics. I just moved ColorVectorSpace over there.

**Comment by timholy** [comment]
I'll post Colors.jl there too. Will you move ColorTypes, once you merge this?

**Comment by SimonDanisch** [comment]
Sure!

2015-08-18 0:40 GMT+02:00 Tim Holy <notifications@github.com>:

**Comment by SimonDanisch** [comment]
Some `@inferred` tests seem to not work on Ubuntu (9eC29dc, 7 day old master) and on windows ( 72c344c, 4 days old master)

Not working:
```Julia
@infrd(eltype(RGB)) 
@test @infrd(colortype(RGBA)) == RGB
@test @infrd(basecolortype(HSVA)) == HSV
```
This is the problem:
```Julia
julia> Base.return_types(colortype, Base.typesof(RGBA))
1-element Array{Any,1}:
 Any
```

The rest seems fine!

**Comment by SimonDanisch** [comment]
As no one besides me is using ColorTypes yet and I'm set on integrating this, I will just merge it!

**Comment by timholy** [comment]
That's what I meant above by
> You have to be running a recent julia for the tests to pass (you need JuliaLang/julia#12645).

Before you switch to it, try this for fun:
```jl
julia> using ColorTypes

julia> c = RGB(rand(),rand(),rand())
RGB{Float64}(0.3187238017125491,0.7814248615656347,0.21993973242405107)

julia> @code_llvm convert(RGBA{Float32}, c)
```

Then upgrade your julia and do the same; watch what happens :smile:.

**Comment by SimonDanisch** [comment]
oh okay, I didn't realize that you mean super recent!
The problem is, that GLVisualize does not seem to work with the recent changes... Didn't have the patience to track down the segfault so far.

**Comment by timholy** [comment]
You could cherry-pick that commit.

**Comment by SimonDanisch** [comment]
`@code_llvm convert(RGBA{Float32}, c)` yields the same result for both versions.
```Julia
julia> @code_llvm convert(RGBA{Float32}, c)

define %RGBA @julia_convert_21915(%jl_value_t*, %RGB*) {
top:
  %2 = load %RGB* %1, align 8
  %3 = extractvalue %RGB %2, 0
  %4 = extractvalue %RGB %2, 1
  %5 = extractvalue %RGB %2, 2
  %6 = fptrunc double %3 to float
  %7 = insertvalue %RGBA undef, float %6, 0
  %8 = fptrunc double %4 to float
  %9 = insertvalue %RGBA %7, float %8, 1
  %10 = fptrunc double %5 to float
  %11 = insertvalue %RGBA %9, float %10, 2
  %12 = insertvalue %RGBA %11, float 1.000000e+00, 3
  ret %RGBA %12
}
```
But `Base.return_types(colortype, Base.typesof(RGBA))` works now =)

**Comment by timholy** [comment]
Ah, shoot, I gave you a version that didn't even use the traits (duh). Here's a better example: 
```jl
julia> @code_llvm coloralpha(basecolortype(c)){eltype(c)}(c)

define %RGBA @julia_call_21452(%jl_value_t*, %RGB*) {
top:
  %2 = load %RGB* %1, align 8
  %3 = extractvalue %RGB %2, 0
  %4 = extractvalue %RGB %2, 1
  %5 = extractvalue %RGB %2, 2
  %6 = insertvalue %RGBA undef, double %3, 0
  %7 = insertvalue %RGBA %6, double %4, 1
  %8 = insertvalue %RGBA %7, double %5, 2
  %9 = insertvalue %RGBA %8, double 1.000000e+00, 3
  ret %RGBA %9
```
Compare julia 0.3:
```jl
julia> @code_llvm coloralpha(basecolortype(c)){eltype(c)}(c)

define %jl_value_t* @julia_RGBA_20946(%jl_value_t*, %jl_value_t**, i32) {
top:
  %3 = getelementptr inbounds %jl_value_t* %0, i64 2, i32 0, !dbg !2624
  %4 = load %jl_value_t** %3, align 8, !dbg !2624, !tbaa %jtbaa_func
  %5 = alloca [4 x %jl_value_t*], align 8
  %.sub = getelementptr inbounds [4 x %jl_value_t*]* %5, i64 0, i64 0
  %6 = getelementptr [4 x %jl_value_t*]* %5, i64 0, i64 2, !dbg !2624
  store %jl_value_t* inttoptr (i64 4 to %jl_value_t*), %jl_value_t** %.sub, align 8
  %7 = getelementptr [4 x %jl_value_t*]* %5, i64 0, i64 1, !dbg !2624
  %8 = load %jl_value_t*** @jl_pgcstack, align 8, !dbg !2624
  %.c = bitcast %jl_value_t** %8 to %jl_value_t*, !dbg !2624
  store %jl_value_t* %.c, %jl_value_t** %7, align 8, !dbg !2624
  store %jl_value_t** %.sub, %jl_value_t*** @jl_pgcstack, align 8, !dbg !2624
  store %jl_value_t* null, %jl_value_t** %6, align 8
  %9 = getelementptr [4 x %jl_value_t*]* %5, i64 0, i64 3
  store %jl_value_t* null, %jl_value_t** %9, align 8
  %10 = getelementptr inbounds %jl_value_t* %4, i64 2, i32 0, !dbg !2628
  %11 = load %jl_value_t** %10, align 8, !dbg !2628, !tbaa %jtbaa_tuplelen
  %12 = getelementptr inbounds %jl_value_t* %11, i64 1, i32 0, !dbg !2628
  %13 = load %jl_value_t** %12, align 8, !dbg !2628
  %14 = icmp eq %jl_value_t* %13, null, !dbg !2628
  br i1 %14, label %err, label %ok, !dbg !2628

err:                                              ; preds = %top
  call void @jl_undefined_var_error(%jl_value_t* inttoptr (i64 140558318027640 to %jl_value_t*)), !dbg !2628
  unreachable

ok:                                               ; preds = %top
  %15 = getelementptr inbounds %jl_value_t* %13, i64 0, i32 0, !dbg !2628
  %16 = load %jl_value_t** %15, align 8, !dbg !2628
  %magicptr = ptrtoint %jl_value_t* %16 to i64, !dbg !2628
  switch i64 %magicptr, label %notf [
    i64 19679504, label %isf
    i64 19547520, label %isf
  ], !dbg !2628

notf:                                             ; preds = %ok
  call void @jl_type_error_rt_line(i8* getelementptr inbounds ([5 x i8]* @_j_str51, i64 0, i64 0), i8* getelementptr inbounds ([6 x i8]* @_j_str10, i64 0, i64 0), %jl_value_t* inttoptr (i64 19679504 to %jl_value_t*), %jl_value_t* %13, i32 415), !dbg !2628
  unreachable

isf:                                              ; preds = %ok, %ok
  %17 = load %jl_value_t** %1, align 8, !dbg !2624
  %18 = getelementptr inbounds %jl_value_t* %13, i64 1, i32 0, !dbg !2628
  %19 = load %jl_value_t** %18, align 8, !dbg !2628, !tbaa %jtbaa_func
  %20 = bitcast %jl_value_t* %19 to %jl_value_t* (%jl_value_t*, %jl_value_t**, i32)*, !dbg !2628
  store %jl_value_t* %17, %jl_value_t** %6, align 8, !dbg !2628
  store %jl_value_t* inttoptr (i64 147557024 to %jl_value_t*), %jl_value_t** %9, align 8, !dbg !2628
  %21 = call %jl_value_t* %20(%jl_value_t* %13, %jl_value_t** %6, i32 2), !dbg !2628
  %22 = load %jl_value_t** %7, align 8, !dbg !2628
  %23 = getelementptr inbounds %jl_value_t* %22, i64 0, i32 0, !dbg !2628
  store %jl_value_t** %23, %jl_value_t*** @jl_pgcstack, align 8, !dbg !2628
  ret %jl_value_t* %21, !dbg !2628
}
```

**Comment by timholy** [comment]
OK, I just pushed https://github.com/JuliaGraphics/Colors.jl. I need to update the README and add some documentation. (I'm trying to add some value, as incentive for people to upgrade. Note the recent performance and testing improvements. But internal documentation will help, too.)

As soon as you push this to JuliaGraphics, then everything will be in its "real" home and we can ask for feedback.

BTW, if you're working on Images at all (to use ImageMagick), then definitely base it on the `teh/colors` branch (the one in PR 340).

**Pull request merged**
